spring:
  liquibase:
    enabled: false
  application:
    name: CookHub
  data:
    mongodb:
      username: ${CH_USER:username}
      password: ${CH_PASSWORD:password}
      uri: mongodb://${CH_HOST:cookhub-db}:27017/${CH_DB_NAME:cookhub}?authSource=admin

server:
  shutdown: graceful

logging:
  level:
    com: info
    org:
      springframework: info

application:
  version: 1.0.0